name: backupy
summary: BackuPy
description: |
  A simple backup program in python with an emphasis on data integrity
  and transparent behaviour.
confinement: strict
base: core22
version: '1.10.1'

parts:
  backupy:
    plugin: python
    source: https://github.com/elesiuta/backupy.git
    source-tag: 'v${SNAPCRAFT_PROJECT_VERSION}'

apps:
  backupy:
    command: bin/backupy
    plugs:
    - home
    - removable-media
    - system-backup
